# Spring properties
spring:
  application:
     name: eureka-client-service #服務名稱
# Discovery Server Access
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/ #Eureka Server的位址
# HTTP Server
server:
  port: 2222   # HTTP (Tomcat) port #服務的埠號