# Spring properties
spring:
  application:
     name: member-service
# Discovery Server Access
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
# HTTP Server
server:
  port: 2223   # HTTP (Tomcat) port